[package]
name = "adder"
version = "0.1.1-alpha.0"
authors = ["Hayato Ito <hayatoito@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

add-one = { path = "../add-one" }
