[package]
name = "add-one"
version = "0.1.11"
authors = ["Hayato Ito <hayatoito@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
