name: nightly
on:
  schedule:
    - cron: 0 0 * * 1
jobs:
  build:
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.rust }}
      - run: rustup default ${{ matrix.rust }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo update
      - run: cargo build --all-features
      - run: cargo test --all-features
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets -- --deny warnings
